version: '3'

services:
  web:
    build: .
    working_dir: /app/todo_quest
    command: php artisan serve --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    tty: true

  db:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root

volumes:
  db-volume:
